### ISSUE TITLE
specify random block

### ISSUE THREAD

**Issue by Edulynch** [Wertik/BlockRegen#13]
nice work bro.
This plugin have a wiki ?
i can specify random block regen with rate
example
Diamond Block rate: 10%
Emerald Block rate: 30%
Iron Block rate: 30%
etc..

Thanks bro

**Comment by Wertik** [comment]
It's possible to specify a percentage. https://github.com/Wertik/BlockRegen/blob/master/blockregen-plugin/src/main/resources/Blocklist.yml#L167

There's no wiki.
