### ISSUE TITLE
onDisable dont regen blocks

### ISSUE THREAD

**Issue by exzolink** [Wertik/BlockRegen#27]
onDisable dont regen blocks due to registering bukkit tasks while disabling

**Comment by Wertik** [comment]
Please provide any relevant information starting with the server version, plugin version, full stracktrace of the error or a way to reproduce the issue reliably.

**Comment by exzolink** [comment]
You cant run tasks while disabling server. Check your revertAll method

**Comment by exzolink** [comment]
@Wertik 
https://pastebin.com/7V0fLexR

**Comment by ExceptedPrism3** [comment]
The same issue over here, it doesn't regen onDisable due to a runnable defect.

**Comment by exzolink** [comment]
@Wertik hello?

**Comment by Wertik** [comment]
This should be fixed in 3.11.2. Sorry for the late response.
