### ISSUE TITLE
Broken on 1.21

### ISSUE THREAD

**Issue by Raidware** [Wertik/BlockRegen#38]
add support 1.21 thanks

**Comment by Wertik** [comment]
Added in 3.10.8, you can download the jar in releases.

**Comment by Raidware** [comment]
> Added in 3.10.8, you can download the jar in releases.

thank you but probably when I change the jar file, the blocks I rented are not renewed. When I look at the BlockRegen folder, the regions.yml inside is reset and even though I paste the old configuration into the file and save it and type /blockregen reload, the blocks I rented still do not refresh.

**Comment by Raidware** [comment]
also is this supports 1.21.1? @Wertik

**Comment by Wertik** [comment]
> > Added in 3.10.8, you can download the jar in releases.
> 
> thank you but probably when I change the jar file, the blocks I rented are not renewed. When I look at the BlockRegen folder, the regions.yml inside is reset and even though I paste the old configuration into the file and save it and type /blockregen reload, the blocks I rented still do not refresh.

That's unfortunate, not really sure how that could've happened. To get the regions back, stop the server (or stop the plugin using a plugin manager), put the old Regions.yml and Data.json in the folder and start it again.

**Comment by Wertik** [comment]
> also is this supports 1.21.1? @Wertik 

Yes, should support 1.21.1 since version 3.10.8

**Comment by Raidware** [comment]
> > > Added in 3.10.8, you can download the jar in releases.
> > 
> > 
> > thank you but probably when I change the jar file, the blocks I rented are not renewed. When I look at the BlockRegen folder, the regions.yml inside is reset and even though I paste the old configuration into the file and save it and type /blockregen reload, the blocks I rented still do not refresh.
> 
> That's unfortunate, not really sure how that could've happened. To get the regions back, stop the server (or stop the plugin using a plugin manager), put the old Regions.yml and Data.json in the folder and start it again.

i tried this bu still same. i have to select regin with tools then i set region and fixed
