### ISSUE TITLE
Issue with saving regen status on reboot.

### ISSUE THREAD

**Issue by Kruseified** [Wertik/BlockRegen#42]
There is a issue where if items have not regenerated prior to server reboot, it causes the items to not regenerate upon start up from the reboot.

**Comment by Wertik** [comment]
Hey, what kind of items? What version of the plugin are you using? If anything under 3.11.4, please update from releases here on GitHub.

**Comment by Kruseified** [comment]
Using latest. And any block, crops and ores are what I have tested and appear to have issues.

**Comment by Wertik** [comment]
Regeneration processes that haven't finished when a server stop occurs are saved and continue upon server start. That is intended and seems like a reasonable behaviour. Is that what you were reporting?

**Comment by Kruseified** [comment]
See, that would be a fine result. But it does not function in that manor. Upon server starting, block states remain as they were directly prior to reboot. (So left blank/not replaced)

**Comment by Wertik** [comment]
I wasn't able to replicate this issue on a clean server. Do you get any errors in the console upon start or stop of the server? Does the server stop in an expected way or does it crash suddenly?

**Comment by Wertik** [comment]
I fixed some issues with regeneration in 3.11.5. It might've fixed yours aswell.

**Comment by Wertik** [comment]
No further response, most likely fixed, closing, reopen if needed
