### ISSUE TITLE
Add action bar messages on block break.

### ISSUE THREAD

**Issue by Kruseified** [Wertik/BlockRegen#43]
Title says it all, needs to also have visibility duration.

action-bar: place message here
visibility-dur: 1 (in seconds)

You should add labels to your repository so as people can label issues appropriately. 

Like; bug and Feature Request

**Comment by Wertik** [comment]
Hey, haven't really anticipated people coming here to get help, they primarily head to the discord server, will add the labels.

I'm not sure how useful this feature would be, it would essentially be notifying you of breaking a block you went there to break.

**Comment by Wertik** [comment]
This feature also seems feasible to achieve anyway through a different plugin and a command. Back when I ran a server we used https://www.spigotmc.org/resources/messageannouncer.5408/ to do such things. I think CMI would also have a command to send an action bar to a player.
